alias ls='ls --color=auto'
alias ll='ls -hals'
alias ps='ps aux'
alias apt='sudo apt'
alias systemctl='sudo systemctl'
alias glog='git log --oneline --graph --color --all --decorate'
alias less='less -R'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
#alias diff='colordiff'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
